.POSIX:
.SUFFIXES:

include config.mk

# flags for compiling
DWLCPPFLAGS = -I. -DWLR_USE_UNSTABLE -D_POSIX_C_SOURCE=200809L \
	-DVERSION=\"$(VERSION)\" $(XWAYLAND)
# DWLDEVCFLAGS = -g -Wpedantic -Wall -Wextra -Wdeclaration-after-statement \
	-Wno-unused-parameter -Wshadow -Wunused-macros -Werror=strict-prototypes \
	-Werror=implicit -Werror=return-type -Werror=incompatible-pointer-types \
	-Wfloat-conversion

# CFLAGS / LDFLAGS
PKGS      = wlroots-0.20 wayland-server libpulse xkbcommon libinput pixman-1 fcft libsystemd $(XLIBS)
DWLCFLAGS = `$(PKG_CONFIG) --cflags $(PKGS)` $(DWLCPPFLAGS) $(DWLDEVCFLAGS) $(CFLAGS)
LDLIBS    = `$(PKG_CONFIG) --libs $(PKGS)` -lm $(LIBS) \
	-Ltray -Wl,-rpath,'$$ORIGIN/tray' -lawltray

# libawlplugins.so: the plugin threads and the bar widgets, dlopen()ed by
# plugin_host.c and reloaded with plugin_restart (see awl_plugin_abi.h).
# plugins/redraw.c stays in dwl, which owns the redraw eventfd.
PLUGINS_SRC := $(filter-out plugins/redraw.c,$(wildcard plugins/*.c))
PLUGINS_OBJ := $(patsubst %.c,%.o,$(PLUGINS_SRC)) plugins.o widgets.o desktop_panel.o awl_config.o
PLUGINS_PKGS = libpulse libsystemd pixman-1
# --as-needed drops config.mk's -lscenefx, which only dwl uses
PLUGINS_LIBS = -Wl,--as-needed `$(PKG_CONFIG) --libs $(PLUGINS_PKGS)` -lm -pthread

DWL_OBJ := dwl.o dwl-log.o util.o drwl.o plugin_host.o desktop.o plugins/redraw.o

# header dependencies, generated by the compiler alongside each object
DEPS := $(patsubst %.o,%.d,$(DWL_OBJ) $(PLUGINS_OBJ))

all: dwl libawlplugins.so
dwl: $(DWL_OBJ) tray/libawltray.so
	rm -f $@
	$(CC) $(DWL_OBJ) $(DWLCFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

# only awl_plugin_entry is exported; everything else binds within the library
$(PLUGINS_OBJ): DWLCFLAGS += -fPIC -fvisibility=hidden
# linked under a temporary name and renamed, so a running dwl that reloads
# mid-build reads either the old or the new library, never half of one
libawlplugins.so: $(PLUGINS_OBJ)
	$(CC) -shared $(PLUGINS_OBJ) $(DWLCFLAGS) $(PLUGINS_LIBS) $(LDFLAGS) -o $@.tmp
	mv -f $@.tmp $@
dwl.o: dwl.c client.h config.h drwl.h config.mk cursor-shape-v1-protocol.h \
	pointer-constraints-unstable-v1-protocol.h wlr-layer-shell-unstable-v1-protocol.h \
	wlr-output-power-management-unstable-v1-protocol.h xdg-shell-protocol.h tray/awl_tray.h
util.o: util.c util.h
.PHONY: tray/libawltray.so
tray/libawltray.so:
	$(MAKE) -C tray

# wayland-scanner is a tool which generates C headers and rigging for Wayland
# protocols, which are specified in XML. wlroots requires you to rig these up
# to your build system yourself and provide them in the include path.
WAYLAND_SCANNER   = `$(PKG_CONFIG) --variable=wayland_scanner wayland-scanner`
WAYLAND_PROTOCOLS = `$(PKG_CONFIG) --variable=pkgdatadir wayland-protocols`

cursor-shape-v1-protocol.h:
	$(WAYLAND_SCANNER) enum-header \
		$(WAYLAND_PROTOCOLS)/staging/cursor-shape/cursor-shape-v1.xml $@
pointer-constraints-unstable-v1-protocol.h:
	$(WAYLAND_SCANNER) enum-header \
		$(WAYLAND_PROTOCOLS)/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml $@
wlr-layer-shell-unstable-v1-protocol.h:
	$(WAYLAND_SCANNER) enum-header \
		protocols/wlr-layer-shell-unstable-v1.xml $@
wlr-output-power-management-unstable-v1-protocol.h:
	$(WAYLAND_SCANNER) server-header \
		protocols/wlr-output-power-management-unstable-v1.xml $@
xdg-shell-protocol.h:
	$(WAYLAND_SCANNER) server-header \
		$(WAYLAND_PROTOCOLS)/stable/xdg-shell/xdg-shell.xml $@

config.h:
	cp config.def.h $@
clean:
	rm -f dwl libawlplugins.so *.o *-protocol.h
	rm -f $(PLUGINS_OBJ) plugins/redraw.o $(DEPS)
	$(MAKE) -C tray clean

dist: clean
	mkdir -p dwl-$(VERSION)/plugins dwl-$(VERSION)/tray
	cp -R LICENSE* Makefile CHANGELOG.md README.md client.h config.def.h \
		config.mk protocols dwl.1 dwl.c dwl.h dwl-log.c dwl-log.h util.c util.h \
		drwl.c drwl.h plugins.c plugins.h widgets.c plugin_host.c plugin_host.h desktop.c desktop.h desktop_panel.c awl_config.c \
		awl_plugin_abi.h dwl.desktop \
		dwl-$(VERSION)
	cp plugins/*.c plugins/*.h dwl-$(VERSION)/plugins
	cp -Rp tray/Makefile tray/*.c tray/*.h tray/*.cpp tray/*.hpp tray/protocol \
		dwl-$(VERSION)/tray
	tar -caf dwl-$(VERSION).tar.gz dwl-$(VERSION)
	rm -rf dwl-$(VERSION)

install: dwl
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	rm -f $(DESTDIR)$(PREFIX)/bin/dwl
	cp -f dwl $(DESTDIR)$(PREFIX)/bin
	chmod 755 $(DESTDIR)$(PREFIX)/bin/dwl
	mkdir -p $(DESTDIR)$(MANDIR)/man1
	cp -f dwl.1 $(DESTDIR)$(MANDIR)/man1
	chmod 644 $(DESTDIR)$(MANDIR)/man1/dwl.1
	mkdir -p $(DESTDIR)$(DATADIR)/wayland-sessions
	cp -f dwl.desktop $(DESTDIR)$(DATADIR)/wayland-sessions/dwl.desktop
	chmod 644 $(DESTDIR)$(DATADIR)/wayland-sessions/dwl.desktop
uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/dwl $(DESTDIR)$(MANDIR)/man1/dwl.1 \
		$(DESTDIR)$(DATADIR)/wayland-sessions/dwl.desktop

.SUFFIXES: .c .o
.c.o:
	$(CC) $(CPPFLAGS) $(DWLCFLAGS) -MMD -MP -o $@ -c $<

# after all rules, so a .d file's target can't become the default goal
-include $(DEPS)
