.POSIX:
.SUFFIXES:

include config.mk

# flags for compiling
AWLCPPFLAGS = -I. -DWLR_USE_UNSTABLE -D_POSIX_C_SOURCE=200809L \
	-DVERSION=\"$(VERSION)\" $(XWAYLAND)
# AWLDEVCFLAGS = -g -Wpedantic -Wall -Wextra -Wdeclaration-after-statement \
	-Wno-unused-parameter -Wshadow -Wunused-macros -Werror=strict-prototypes \
	-Werror=implicit -Werror=return-type -Werror=incompatible-pointer-types \
	-Wfloat-conversion

# CFLAGS / LDFLAGS
PKGS      = wlroots-0.20 wayland-server libpulse xkbcommon libinput pixman-1 fcft libsystemd $(XLIBS)
AWLCFLAGS = `$(PKG_CONFIG) --cflags $(PKGS)` $(AWLCPPFLAGS) $(AWLDEVCFLAGS) $(CFLAGS)
LDLIBS    = `$(PKG_CONFIG) --libs $(PKGS)` -lm $(LIBS) \
	-Ltray -Wl,-rpath,'$$ORIGIN/tray' -lawltray

# libawlplugins.so: the plugin threads and the bar widgets, dlopen()ed by
# plugin_host.c and reloaded with plugin_restart (see awl_plugin_abi.h).
# plugins/redraw.c stays in awl, which owns the redraw eventfd.
PLUGINS_SRC := $(filter-out plugins/redraw.c,$(wildcard plugins/*.c))
PLUGINS_OBJ := $(patsubst %.c,%.o,$(PLUGINS_SRC)) plugins.o widgets.o desktop_panel.o awl_config.o \
	wuffs/wuffs.o
PLUGINS_PKGS = libpulse libsystemd pixman-1 fcft
# --as-needed drops config.mk's -lscenefx, which only awl uses
PLUGINS_LIBS = -Wl,--as-needed `$(PKG_CONFIG) --libs $(PLUGINS_PKGS)` -lm -pthread

AWL_OBJ := awl.o awl-log.o awl_dict.o util.o awl_draw.o plugin_host.o desktop.o background.o plugins/redraw.o

# header dependencies, generated by the compiler alongside each object
DEPS := $(patsubst %.o,%.d,$(AWL_OBJ) $(PLUGINS_OBJ))

all: awl libawlplugins.so
awl: $(AWL_OBJ) tray/libawltray.so
	rm -f $@
	$(CC) $(AWL_OBJ) $(AWLCFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

# only awl_plugin_entry is exported; everything else binds within the library
$(PLUGINS_OBJ): AWLCFLAGS += -fPIC -fvisibility=hidden
# linked under a temporary name and renamed, so a running awl that reloads
# mid-build reads either the old or the new library, never half of one
libawlplugins.so: $(PLUGINS_OBJ)
	$(CC) -shared $(PLUGINS_OBJ) $(AWLCFLAGS) $(PLUGINS_LIBS) $(LDFLAGS) -o $@.tmp
	mv -f $@.tmp $@
awl.o: awl.c client.h config_awl.h config_plugins.def.h awl_draw.h config.mk cursor-shape-v1-protocol.h \
	pointer-constraints-unstable-v1-protocol.h wlr-layer-shell-unstable-v1-protocol.h \
	wlr-output-power-management-unstable-v1-protocol.h xdg-shell-protocol.h tray/awl_tray.h
util.o: util.c util.h
.PHONY: tray/libawltray.so
tray/libawltray.so:
	$(MAKE) -C tray

# wayland-scanner is a tool which generates C headers and rigging for Wayland
# protocols, which are specified in XML. wlroots requires you to rig these up
# to your build system yourself and provide them in the include path.
WAYLAND_SCANNER   = `$(PKG_CONFIG) --variable=wayland_scanner wayland-scanner`
WAYLAND_PROTOCOLS = `$(PKG_CONFIG) --variable=pkgdatadir wayland-protocols`

cursor-shape-v1-protocol.h:
	$(WAYLAND_SCANNER) enum-header \
		$(WAYLAND_PROTOCOLS)/staging/cursor-shape/cursor-shape-v1.xml $@
pointer-constraints-unstable-v1-protocol.h:
	$(WAYLAND_SCANNER) enum-header \
		$(WAYLAND_PROTOCOLS)/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml $@
wlr-layer-shell-unstable-v1-protocol.h:
	$(WAYLAND_SCANNER) enum-header \
		protocols/wlr-layer-shell-unstable-v1.xml $@
wlr-output-power-management-unstable-v1-protocol.h:
	$(WAYLAND_SCANNER) server-header \
		protocols/wlr-output-power-management-unstable-v1.xml $@
xdg-shell-protocol.h:
	$(WAYLAND_SCANNER) server-header \
		$(WAYLAND_PROTOCOLS)/stable/xdg-shell/xdg-shell.xml $@

# on the first build, copied from their .def.h
config_awl.h config_plugins.h:
	cp $(@:.h=.def.h) $@
awl_config.o: config_plugins.h
clean:
	rm -f awl libawlplugins.so *.o *-protocol.h
	rm -f $(PLUGINS_OBJ) plugins/redraw.o $(DEPS)
	$(MAKE) -C tray clean

dist: clean
	mkdir -p awl-$(VERSION)/plugins awl-$(VERSION)/tray awl-$(VERSION)/wuffs
	cp -R LICENSE Makefile README.md client.h config_awl.def.h config_plugins.def.h \
		config.mk protocols awl.c awl.h awl-log.c awl-log.h util.c util.h \
		awl_draw.c awl_draw.h plugins.c plugins.h widgets.c plugin_host.c plugin_host.h desktop.c desktop.h desktop_panel.c background.c background.h awl_config.c \
		awl_plugin_abi.h awl.desktop \
		awl-$(VERSION)
	cp plugins/*.c plugins/*.h awl-$(VERSION)/plugins
	cp wuffs/*.c wuffs/*.h awl-$(VERSION)/wuffs
	cp -Rp tray/Makefile tray/*.c tray/*.h tray/*.cpp tray/*.hpp tray/protocol \
		awl-$(VERSION)/tray
	tar -caf awl-$(VERSION).tar.gz awl-$(VERSION)
	rm -rf awl-$(VERSION)

.SUFFIXES: .c .o
.c.o:
	$(CC) $(CPPFLAGS) $(AWLCFLAGS) -MMD -MP -o $@ -c $<

# after all rules, so a .d file's target can't become the default goal
-include $(DEPS)
